### ISSUE TITLE
Allow users to add new company

### ISSUE THREAD

**Issue by hadiasghari** [data-in-sight/datarights#100]
I'd like users to be able to add a new company that doesn't exist in the list. 

-    Only the user sees them; once admin approves, other see them too
-    Have a link to the companies privacy policy URL (so we can check contact address/email)
-    Company contact  (mail + email)
-    Comments
-    Sector should default to 'others' (admin can update); language default to English.

Related, users should also be able to report contact info they think is wrong. => link to forum/commu channel

@postdigital if you give a UX quickly @mani47 can use that -- otherwise bootstrap default is good.

**Comment by mani47** [comment]
Feature added in #104
